import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const futuraTwoMedium = localFont({
  src: "../../public/fonts/futura-no-2-medium-dee.ttf",
  variable: "--font-futura-pt-medium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='bg-stone-300' lang="en">
      <body
        className={`${futuraTwoMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
